services:
  postgres:
    image: postgres:16
    container_name: postgres-db-truck-monitoring
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: truck_monitoring
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: truck-monitoring-app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "truck monitoring application"
      DB_URL: jdbc:postgresql://postgres:5432/truck_monitoring
      DB_USER: postgres
      DB_PASSWORD: postgres
      SERVER_PORT: 8080
    # если ты собираешь jar-файл через gradle/maven
    command: ["java", "-jar", "app.jar"]

volumes:
  pgdata:
