spring:
  application:
    name: truck monitoring application

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/truck_monitoring}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

server:
  port: ${SERVER_PORT:8080}
